/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/Chat.vue')['default']
    ConnectionManager: typeof import('./src/components/ConnectionManager.vue')['default']
    Lobby: typeof import('./src/components/Lobby.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    ReadyIcon: typeof import('./src/components/1st Level/ReadyIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stats: typeof import('./src/components/Stats.vue')['default']
  }
}
