/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
/* prettier-ignore */
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/Chat.vue')['default']
    ConnectionManager: typeof import('./src/components/ConnectionManager.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    ReadyIcon: typeof import('./src/components/Atoms/ReadyIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
