/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConnectionState: typeof import('./src/components/ConnectionState.vue')['default']
    TestWebSocket: typeof import('./src/components/TestWebSocket.vue')['default']
  }
}
